- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.10'

- name: Export environment variables
  run: |
    echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
    echo "WEBSITE_HOSTING=${{ secrets.WEBSITE_HOSTING }}" >> $GITHUB_ENV
    echo "AZURE_POSTGRESQL_CONNECTIONSTRING=${{ secrets.AZURE_POSTGRESQL_CONNECTIONSTRING }}" >> $GITHUB_ENV
    echo "DJANGO_SETTINGS_MODULE=core.deployment" >> $GITHUB_ENV

- name: Install dependencies
  run: |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r backend/requirements.txt

- name: Collect static files
  run: |
    source venv/bin/activate
    cd backend
    python manage.py collectstatic --noinput

- name: Package application
  run: |
    zip -r release.zip backend

- name: Deploy to Azure Web App
  uses: azure/webapps-deploy@v3
  with:
    app-name: 'chemisttasker'
    slot-name: 'Production'
    package: release.zip
